name: Deploy to Mittwald SpaceServer 🚀

on:
  push:
    branches: [main]
    # Sustainability: Don't trigger build for updated README
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Pull repository into the current pipeline
      - name: Pull repository
        uses: actions/checkout@v3

      # Setup NodeJS LTS
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install and build via npm 🔧" 
        run: |
          npm ci
          npm run build

      - name: "Debug: Show generated files"
        run: |
          ls -ls

      # rsync (via SSH key auth)
      # https://github.com/Burnett01/rsync-deployments
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          # be careful with --delete option! (but use it later if path is correct)
          switches: -avzr --delete
          # local path, defaults to GITHUB_WORKSPACE and is relative to it
          path: /
          # remote_path, something like /html/sveltekit-p-n238roi4/ 
          # remote_path: ${{ secrets.SSH_PATH }}
          remote_path: /html/sveltekit-demo-u7qzj/
          remote_host: ssh.fabbenstedt.project.host
          remote_user: ${{ secrets.SSH_USER }}
          # The private key, public key part must be added to Mittwald project/user
          remote_key: ${{ secrets.SSH_KEY }}
